<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:sans-serif; font-size:11px; color:#1f2937; }
  .header { background:#1e3a5f; color:white; padding:16px 22px; margin-bottom:16px; }
  .header h1 { font-size:17px; font-weight:700; }
  .header p { font-size:10px; opacity:.8; margin-top:2px; }
  .meta { float:right; text-align:right; margin-top:-34px; font-size:10px; opacity:.9; }
  .summary { display:table; width:100%; margin-bottom:16px; border-collapse:separate; border-spacing:6px; }
  .scard { display:table-cell; width:25%; background:#f8fafc; border:1px solid #e2e8f0; border-radius:5px; padding:9px 12px; }
  .scard .lbl { font-size:9px; color:#64748b; text-transform:uppercase; margin-bottom:2px; }
  .scard .val { font-size:15px; font-weight:700; color:#1e3a5f; }
  .scard.green .val { color:#16a34a; }
  .drawer-section { margin-bottom:18px; }
  .drawer-title { background:#fef3c7; color:#92400e; padding:6px 12px; border-radius:5px; font-size:11px; font-weight:700; margin-bottom:6px; display:inline-block; }
  .drawer-stats { display:table; width:100%; margin-bottom:8px; border-collapse:separate; border-spacing:5px; }
  .dstat { display:table-cell; background:#f8fafc; border:1px solid #e2e8f0; border-radius:4px; padding:7px 10px; }
  .dstat .lbl { font-size:9px; color:#64748b; margin-bottom:2px; }
  .dstat .val { font-size:13px; font-weight:700; color:#1e3a5f; }
  table.inv { width:100%; border-collapse:collapse; margin-top:6px; }
  table.inv thead tr { background:#1e3a5f; color:white; }
  table.inv thead th { padding:6px 9px; text-align:left; font-size:9px; text-transform:uppercase; }
  table.inv thead th.r { text-align:right; }
  table.inv tbody tr:nth-child(even) { background:#f8fafc; }
  table.inv tbody td { padding:5px 9px; border-bottom:1px solid #e2e8f0; font-size:9px; }
  table.inv tbody td.r { text-align:right; }
  .badge { background:#e0e7ff; color:#3730a3; padding:1px 5px; border-radius:99px; font-size:8px; }
  .badge.green { background:#dcfce7; color:#166534; }
  .footer { margin-top:12px; padding-top:8px; border-top:1px solid #e2e8f0; display:table; width:100%; }
  .footer .l { display:table-cell; font-size:9px; color:#94a3b8; }
  .footer .r { display:table-cell; text-align:right; font-size:9px; color:#94a3b8; }
</style>
</head>
<body>
<div class="header">
  <h1>MediStock POS — HOD Pharmacy Sales Report</h1>
  <p>Generated by: {{ $user->name }} (HOD Pharmacy)</p>
  <div class="meta">
    Period: <strong>{{ \Carbon\Carbon::parse($from)->format('d M Y') }} — {{ \Carbon\Carbon::parse($to)->format('d M Y') }}</strong><br>
    Generated: {{ now()->format('d M Y, H:i') }}
  </div>
</div>

<div class="summary">
  <div class="scard">
    <div class="lbl">Total Revenue</div>
    <div class="val">NGN {{ number_format($summary['total_amount'],2) }}</div>
    <div style="font-size:9px;color:#64748b">{{ $summary['total_count'] }} invoices</div>
  </div>
  <div class="scard">
    <div class="lbl">Normal Sales</div>
    <div class="val">NGN {{ number_format($summary['normal_amount'],2) }}</div>
  </div>
  <div class="scard green">
    <div class="lbl">Insurance Co-payments</div>
    <div class="val">NGN {{ number_format($summary['insurance_amount'],2) }}</div>
  </div>
  <div class="scard">
    <div class="lbl">All Drawers</div>
    <div class="val">3 Drawers</div>
  </div>
</div>

@foreach([1,2,3] as $num)
@php $d = $drawerSales[$num]; $invs = $drawerInvoices[$num]; @endphp
<div class="drawer-section">
  <div class="drawer-title">🗄 Drawer {{ $num }}</div>
  <div class="drawer-stats">
    <div class="dstat"><div class="lbl">Total</div><div class="val">NGN {{ number_format($d['total_amount'],2) }}</div></div>
    <div class="dstat"><div class="lbl">Normal ({{ $d['normal_count'] }})</div><div class="val">NGN {{ number_format($d['normal_amount'],2) }}</div></div>
    <div class="dstat"><div class="lbl">Insurance ({{ $d['insurance_count'] }})</div><div class="val">NGN {{ number_format($d['insurance_amount'],2) }}</div></div>
    <div class="dstat"><div class="lbl">Invoices</div><div class="val">{{ $d['total_count'] }}</div></div>
  </div>
  @if($invs->count() > 0)
  <table class="inv">
    <thead><tr>
      <th>#</th><th>Invoice</th><th>Patient</th><th>Type</th><th>Cashier</th><th class="r">Amount</th><th>Paid At</th>
    </tr></thead>
    <tbody>
      @foreach($invs as $i => $inv)
      <tr>
        <td>{{ $i+1 }}</td>
        <td style="font-family:monospace">{{ $inv->invoice_number }}</td>
        <td>{{ $inv->patient_name }}</td>
        <td>
          @if($inv->isInsurance())
          <span class="badge green">{{ $inv->insuranceScheme?->name }}</span>
          @else
          <span class="badge">Normal</span>
          @endif
        </td>
        <td>{{ $inv->createdBy?->name }}</td>
        <td class="r">NGN {{ number_format($inv->total_amount,2) }}</td>
        <td>{{ $inv->paid_at?->format('d M Y H:i') }}</td>
      </tr>
      @endforeach
    </tbody>
  </table>
  @else
  <p style="font-size:10px;color:#94a3b8;padding:8px 0">No invoices for this drawer in the selected period.</p>
  @endif
</div>
@endforeach

<div class="footer">
  <div class="l">MediStock POS — HOD Pharmacy Report — Confidential</div>
  <div class="r">{{ now()->format('d/m/Y H:i:s') }}</div>
</div>
</body>
</html>