<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:sans-serif; font-size:11px; color:#1f2937; }
  .header { background:#1e3a5f; color:white; padding:16px 22px; margin-bottom:16px; }
  .header h1 { font-size:17px; font-weight:700; }
  .header p { font-size:10px; opacity:.8; margin-top:2px; }
  .meta { float:right; text-align:right; margin-top:-34px; font-size:10px; opacity:.9; }
  .drawer-section { margin-bottom:18px; }
  .drawer-title { background:#fef3c7; color:#92400e; padding:6px 12px; border-radius:5px; font-size:11px; font-weight:700; margin-bottom:6px; display:inline-block; }
  table.main { width:100%; border-collapse:collapse; margin-bottom:6px; }
  table.main thead tr { background:#1e3a5f; color:white; }
  table.main thead th { padding:7px 10px; text-align:left; font-size:9px; text-transform:uppercase; }
  table.main thead th.r { text-align:right; }
  table.main tbody tr:nth-child(even) { background:#f8fafc; }
  table.main tbody td { padding:6px 10px; border-bottom:1px solid #e2e8f0; font-size:10px; }
  table.main tbody td.r { text-align:right; }
  table.main tfoot tr { background:#e2e8f0; }
  table.main tfoot td { padding:7px 10px; font-weight:700; font-size:10px; }
  table.main tfoot td.r { text-align:right; }
  .alert-section { margin-bottom:18px; }
  .alert-title { font-size:12px; font-weight:700; margin-bottom:8px; }
  .alert-title.red { color:#dc2626; }
  .alert-title.amber { color:#d97706; }
  .red-badge { background:#fee2e2; color:#dc2626; padding:2px 7px; border-radius:99px; font-size:9px; font-weight:600; }
  .amber-badge { background:#fef3c7; color:#d97706; padding:2px 7px; border-radius:99px; font-size:9px; font-weight:600; }
  .footer { margin-top:12px; padding-top:8px; border-top:1px solid #e2e8f0; display:table; width:100%; }
  .footer .l { display:table-cell; font-size:9px; color:#94a3b8; }
  .footer .r { display:table-cell; text-align:right; font-size:9px; color:#94a3b8; }
</style>
</head>
<body>
<div class="header">
  <h1>MediStock POS — HOD Pharmacy Stock Report</h1>
  <p>Generated by: {{ $user->name }} (HOD Pharmacy)</p>
  <div class="meta">
    Date: <strong>{{ now()->format('d M Y') }}</strong><br>
    Generated: {{ now()->format('H:i') }}
  </div>
</div>

{{-- Stock Per Drawer --}}
@foreach([1,2,3] as $num)
<div class="drawer-section">
  <div class="drawer-title">🗄 Drawer {{ $num }} — {{ $drawerStock[$num]->count() }} medicines · {{ $drawerStock[$num]->sum('quantity_remaining') }} total units</div>
  @if($drawerStock[$num]->count() > 0)
  <table class="main">
    <thead><tr>
      <th>Medicine</th><th>Batch #</th><th>Expiry Date</th><th class="r">Qty Remaining</th><th>Status</th>
    </tr></thead>
    <tbody>
      @foreach($drawerStock[$num] as $s)
      <tr>
        <td><strong>{{ $s->batch->medicine->name }}</strong></td>
        <td style="font-family:monospace">{{ $s->batch->batch_number }}</td>
        <td>{{ $s->batch->expiry_date->format('d M Y') }}</td>
        <td class="r"><strong>{{ $s->quantity_remaining }}</strong></td>
        <td>
          @if($s->quantity_remaining < 20)
          <span class="red-badge">Low Stock</span>
          @elseif($s->batch->expiry_date <= now()->addDays(30))
          <span class="amber-badge">Expiring Soon</span>
          @else
          <span style="color:#16a34a;font-size:9px">✓ OK</span>
          @endif
        </td>
      </tr>
      @endforeach
    </tbody>
    <tfoot>
      <tr>
        <td colspan="3">Total</td>
        <td class="r">{{ $drawerStock[$num]->sum('quantity_remaining') }} units</td>
        <td></td>
      </tr>
    </tfoot>
  </table>
  @else
  <p style="font-size:10px;color:#94a3b8;padding:6px 0">No stock allocated to this drawer.</p>
  @endif
</div>
@endforeach

{{-- Low Stock Alerts --}}
@if($lowStock->count() > 0)
<div class="alert-section">
  <div class="alert-title red">⚠ Low Stock Alert (Below 20 Units)</div>
  <table class="main">
    <thead><tr><th>Medicine</th><th>Batch #</th><th class="r">Qty Remaining</th></tr></thead>
    <tbody>
      @foreach($lowStock as $s)
      <tr>
        <td>{{ $s->batch->medicine->name }}</td>
        <td style="font-family:monospace">{{ $s->batch->batch_number }}</td>
        <td class="r"><span class="red-badge">{{ $s->quantity_remaining }} units</span></td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>
@endif

{{-- Expiring Soon --}}
@if($expiring->count() > 0)
<div class="alert-section">
  <div class="alert-title amber">🕐 Expiring Within 30 Days</div>
  <table class="main">
    <thead><tr><th>Medicine</th><th>Batch #</th><th>Expiry Date</th><th class="r">Qty</th></tr></thead>
    <tbody>
      @foreach($expiring as $s)
      <tr>
        <td>{{ $s->batch->medicine->name }}</td>
        <td style="font-family:monospace">{{ $s->batch->batch_number }}</td>
        <td><span class="amber-badge">{{ $s->batch->expiry_date->format('d M Y') }}</span></td>
        <td class="r">{{ $s->quantity_remaining }}</td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>
@endif

<div class="footer">
  <div class="l">MediStock POS — HOD Pharmacy Stock Report — Confidential</div>
  <div class="r">{{ now()->format('d/m/Y H:i:s') }}</div>
</div>
</body>
</html>